[tool.poetry]
name = "nut"
version = "1.0.0"
description = ""
authors = ["karrni <24398546+karrni@users.noreply.github.com>"]

[tool.poetry.scripts]
nut = "nut.main:main"

[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.27.1"
XlsxWriter = "^3.0.3"
PyYAML = "^6.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 119

[tool.isort]
profile = "black"
line_length = 119
